server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    nacos:
      discovery:
        # 指定 Nacos Server 的地址
        server-addr: localhost:8848
        # 服务发现 的领域模型：
        # Namespace -> Group -> Service -> Cluster -> Instance
        # 指定 namespace ( dev - dev env namespace )
        namespace: cb472fa5-5350-44b8-b576-d645c2920442
        # 指定 cluster 集群名称
#        cluster-name: Guangzhou
        cluster-name: Shanghai
        # 指定 metadata 信息
        metadata:
          instance: B
          version: V2
    inetutils:
      preferredNetworks:
        - 192.168.1
#        - 192.168

  application:
    # 指定 服务名称（使用'-'分隔）
    name: user-center