server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

spring:

  # MySQL Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        # 指定 Nacos Server 的地址
        server-addr: localhost:8848
        # Ali Cloud Server Address IP: 192.168.1.250
#        server-addr: 192.168.1.250:8848
        # 服务发现 的领域模型：
        # Namespace -> Group -> Service -> Cluster -> Instance
        # 指定 namespace ( dev - dev env namespace )
        namespace: cb472fa5-5350-44b8-b576-d645c2920442
        # 指定 cluster 集群名称
#        cluster-name: Guangzhou
        cluster-name: Shanghai
        # 指定 metadata 信息
        metadata:
          instance: B
          version: V1
    inetutils:
      preferredNetworks:
        - 192.168.1
#        - 192.168

    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          # 用来指定 Topic
          # 必须与 bindings.output 的 destination 相同
          destination: stream-test-topic
          # 如果用的是RocketMQ，一定要设置 group，否则应用不能启动
          # 如果用的是其他MQ，可以留空
          group: binder-group
        my-input:
          destination: stream-my-topic
          # 如果用的是RocketMQ，一定要设置 group，否则应用不能启动
          # 如果用的是其他MQ，可以留空
          group: my-group

  application:
    # 指定 服务名称（使用'-'分隔）
    name: user-center

rocketmq:
  name-server: localhost:9876

#logging:
#  level:
#    com:
#      spring:
#        ibatis:
#          User: DEBUG
#
#    org:
#      springframework: WARN
#
logging:
  config: classpath:logback-dev.xml
  level:
    com.com.example.demo.domain.entity.user: debug